name: p-pal

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  printing-secret:
    runs-on: ubuntu-latest
    steps:
    - name: generate
      id: generate
      run: | 
        secret=`echo $RANDOM`
        echo "::add-mask::$secret"
        echo "secret=$secret" >> $GITHUB_OUTPUT
    - name: print
      run: |
        echo "generated secret is : ${SECRET}"
      env:
        SECRET: ${{ steps.generate.outputs.secret }}
    outputs:
     secret: ${{ steps.generate.outputs.secret }} 
  fetch-secret:
    runs-on: ubuntu-latest
    needs: [printing-secret]
    steps:
    - name: fetch
      id: fetch
      run: |
        echo "fetched secret is : ${FETCHED_SECRET}"
      env:
        FETCHED_SECRET: ${{ needs.printing-secret.outputs.secret }}
